version: 2.1

orbs:
  python: circleci/python@0.2.1

steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command

workflows:
  main:
    jobs:
      - build-and-test
